---
language: ruby
rvm:
  - 2.1.2
script:
- script/cibuild
sudo: false
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
  - gh-pages
